apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Prometheus runs on host network at localhost:9090
    url: http://127.0.0.1:9090
    isDefault: true
    editable: true
