{{- if and .Values.observability.metrics.enabled .Values.observability.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aos.fullname" . }}
  labels:
    {{- include "aos.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aos.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.observability.metrics.serviceMonitor.path }}
      interval: {{ .Values.observability.metrics.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
